### ISSUE TITLE
Offer a way to directly include the newsletter signup in a website

### ISSUE THREAD

**Issue by jancborchardt** [phpList/phpList#15]
(I assume this is the correct repo to use going forward instead of phpList3, let me know if not @samtuke :)

What would be incredibly useful is a small building block / widget of HTML + JS which allows people to simply add an input field to a website (like the frontpage) where people directly put their email address.
This would simplify the flow a lot for users.

For example, compare the direct email input with subscribe button on http://www.theatlantic.com vs the linked button at https://nextcloud.com – there we could simply have an input field + button at the bottom of the page, and that’s all that subscribers would ever see. No extra page load and no redirect to different interface = probably more signups. :)

**Comment by samtuke** [comment]
Hi Jan, thanks for the proposal :)
We provide auto-generated code snippets for inserting AJAX signup forms to lists. E.g.:

https://www.phplist.com/ajaxdemo
https://www.raspberrypi.org/weekly/

These are also customisable from within phpList (set the text in the form and on success).

Is that what you meant?

**Comment by jancborchardt** [comment]
Ah cool, wasn’t aware of that! (Was the one thing I forgot to ask during our meeting.) Disregard this in that case, it’s exactly what I meant. :)
