### ISSUE TITLE
"phone home" - slow admin panel

### ISSUE THREAD

**Issue by wtps0n** [phpList/phpList#16]
Hi,

I'm installed phplist for one of my firends. Latety he complains that admin panel is working very slowly. First we thought that could be mySQL problem. But after tuning changes admin panel still works sloooowly.

After some investigation :-) I suspected a "newsfeed" script which is connecting to phlist.org for news. After disabling it (by commenting the whole lists/admin/ui/dressprow/rssfeed.php) admin panel working very quickly.

I've checked this code. Well, I don't have patch to correct this script, but I'll try to write some thoughts how it could work (maybe quicker):

1. Check if there is "cache" of feeds: file or mysql
2. Check if this "cache" is quite fresh - let's say 1 day/week/moth. It could be a config parameter
3. if cache is "out of date" (or does not exists) download it from phplist.org (do "phone home").
4. Display news on panel (last N entries) from cache.

I think such mechanism will make less "calls" to your servers, users will see that admin panel is working faster. Also phplist is not a news portal :-))) so changes are not published every minute.

I hope my suggestions will help you with your work

**Comment by bramley** [comment]
The problem has already been fixed but not yet released. You can install the modified files as described here https://discuss.phplist.org/t/is-3-2-5-much-slower-than-2-10-18/1894/6 or copy them from the phplist-ui-dressprow repository.

**Comment by wtps0n** [comment]
OK. As I can see my suggestions are coded now :-)

I can wait for new release. That's no problem. Currently as I wrote I commented out the whole current code,

Thanks a lot for your replay.
