### ISSUE TITLE
Add Travis builds

### ISSUE THREAD

**Issue by oliverklee** [phpList/phpList#19]
This is a request to the project owners: Could you please set up Travis builds for this project, a .travis.yml and a master build status badge in the README?

Thanks!

**Comment by oliverklee** [comment]
I can also provide the .travis.yml and the status badge once the Travis builds are set up.

**Comment by oliverklee** [comment]
@michield Could you please have a look at #22 and set up Travis builds for this repository once #22 is merged? (Setting up the Travis builds is the only thing I cannot do via PRs. And changing the GitHub project settings, of course.) Thanks!

**Comment by michield** [comment]
https://travis-ci.org/phpList/phpList
