### ISSUE TITLE
Drop StyleCI from the CI process

### ISSUE THREAD

**Issue by oliverklee** [phpList/phpList#38]
I'd like to have PHP_CodeSniffer only as the style rules of the CI then will be the same as of the grumphp pre-commit hook. Also, this will allow us to modify the rules with a configuration file in the repository.

**Comment by michield** [comment]
ok, sure. I've never been fond of StyleCI. I don't think they've ever given me a thumbs up...

I'll take it out

**Comment by oliverklee** [comment]
Thanks! ❤️
