### ISSUE TITLE
How to do Domain throttling map in phplist

### ISSUE THREAD

**Issue by ttmubarak** [phpList/phpList#40]
Hello, 

Please any one tell me , how to do domain throttling map in phplist software. Please give some idea , how to do this. 

Thank you

**Comment by michield** [comment]
All you need to do is [install the domain throttle plugin](https://www.google.co.uk/search?client=ubuntu&channel=fs&q=how+to+install+a+phplist+plugin&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=432jWJnwC66N8QfAhrKgAQ)
