### ISSUE TITLE
Where is the autoload of /vendor ?

### ISSUE THREAD

**Issue by 7starsone** [phpList/phpList#41]
Hello,
:-) please, can you explain why autoload.php from /vendor

is not included?

so, how it works?
thanks

**Comment by samtuke** [comment]
@7starsone It sounds like composer may not have been initialised inside your phpList 4 directory. Please run ```composer install``` inside your phpList 4 directory. You will need to [download](https://getcomposer.org/download/) or install composer itself first (so that the ```composer``` command is available).

**Comment by oliverklee** [comment]
@samtuke Usually, the `vendor/` directory is excluded from git as it is indeed expected to be filled by doing a `composer` install.
