### ISSUE TITLE
Restore config.ini

### ISSUE THREAD

**Issue by tarekdj** [phpList/phpList#7]
I noticed that config.ini has been removed. I would be good to have a default.config.ini or example.config.ini file providing default config values.

**Comment by michield** [comment]
Yes, agree. It's here: https://github.com/phpList/phpList/commit/529c15554c5e13d06451a9c9f43e07220807318c

Maybe just renaming it would have been better?

**Comment by michield** [comment]
I've re-added it as config.ini.dist
