### ISSUE TITLE
Symfony framework [question]

### ISSUE THREAD

**Issue by scaytrase** [phpList/phpList#9]
Hi!

As soon as you are already using some Symfony2 components, why not using the Symfony2 Fullstack to bootstrap application development? I think this will make code more consistent and incapsulated i.e. with using container instead of global constants and static classes and ini config. Also it's provides essential libraries, like Doctrine2 ORM and Swiftmailer which allows you to focus on business logic and fits better to OO style of this version

**Comment by michield** [comment]
At this stage we try to be framework independent and not enforce a certain route.

**Comment by scaytrase** [comment]
All these components are fully independent. That's why I like symfony. You can consequentially inject and substitute new components one by one and later bind with together to fullstack, if you like them.

The main purpose of suggesting %any_framework_name% is that using a framework you make it easier to contribute to code for a huge amount of people, who uses the same framework or components.

**Comment by tarekdj** [comment]
I'll close this for now. Feel free to re-open at any time.
